### PR TITLE
More small UI fixes

### LINKED ISSUE #295: Small desktop dashboard layout changes
## Description
Screenshot 2023-05-12 at 1 53 18 PM
bring everything more in line with our figma! 

## Todos

These points are rough guidelines. **Please** feel free to discuss the best way to design this component with others on the team!

- [x] decrease rounding on desktop 
- [x] change font size, weight of headers
- [ ] add headers correspondingly 
- [x] refactor graph to display legend to the side 

## Useful links

- [figma](https://www.figma.com/file/Y2IIxfo496bwxFsz8zo9hI/pv-sites-mobile?type=design&node-id=0-1&t=wZHhGKhlTGSY8IGx-0)

### LINKED ISSUE #302: Restyle sites page on mobile
## Description

Here's what we currently have 
image
Here's the figma
image

### PR DESCRIPTION
**Pull request by ericcccsliu**
## Status:
:rocket: Ready

## Description
Closes #302, closes #295 

Also fixes apparent bug in mobile sites page, where loading was showing even if forecast data was available. Changes various text sizes throughout the app to be mobile responsive and consistent with the Figma. Adds option to site graph to apply smoothing through moving average, applies smoothing on site pages and desktop sidebar. 

image
Screenshot 2023-05-19 at 9 51 09 AM

### CODE REVIEW

File: lib/components/dashboard-modules/NumberDisplay.tsx [hunk 1]
```diff
@@ -9,17 +10,21 @@ interface Props {
...
           isLoading ? skeleton : ``
         }`}
       >
         {title}
       </div>
       <div
-        className={`text-2xl font-semibold leading-none text-ocf-yellow transition-all md:leading-none ${
+        className={`${
+          isMobile ? 'text-xl' : 'text-2xl'
+        } font-semibold leading-none text-ocf-yellow transition-all md:leading-none ${
```
Comment (AndrewLester) [inline lib/components/dashboard-modules/NumberDisplay.tsx]: Can this use of `isMobile` be replaced with a `md:`?

**Review by AndrewLester — APPROVED** [review]
Are there any hydration issues caused by the addition of the mobile screen size hooks?

I know we had some in the past with related things. I think we could use custom Tailwind breakpoints at least for the dashboard stuff in that case: https://tailwindcss.com/docs/screens

**Review by AndrewLester — APPROVED** [review]
Are there any hydration issues caused by the addition of the mobile screen size hooks?

I know we had some in the past with related things. I think we could use custom Tailwind breakpoints at least for the dashboard stuff in that case: https://tailwindcss.com/docs/screens
