### PR TITLE
Bug fixes and styling improvements

### LINKED ISSUE #201: Expected Output component not vertically aligned
**Describe the bug**
The text in the expected output component on the dashboard page is not vertically aligned. However, both the expected output component and sunny time frame render the same component (NumberDisplay), yet only the expected output component is misaligned.

Refer to `components\dashboard-modules\ExpectedTotalOutput.tsx` to see the issue with the NumberDisplay render
```const ExpectedTotalOutput: FC<{ siteUUID: string }> = ({ siteUUID }) => {
  const { forecastData } = useSiteData(siteUUID);
  return (
    <NumberDisplay
      title="Today's Expected Output"
      value={
        forecastData
          ? getTotalExpectedOutput(forecastData.forecast_values)
              .toFixed(2)
              .toString() + ' kWh'
          : 'Loading'
      }
    />
  );
};
```

**To Reproduce**

1. Go to dashboard page
2. View the Expected Output component
3. See error

**Expected behavior**
The text within the component should be vertically aligned #

### LINKED ISSUE #204: Change graph threshold to a percentage of capacity
Screen Shot 2023-04-10 at 4 05 46 PM

Currently it's a fixed number of kW—I don't know how we haven't fixed this yet.

### LINKED ISSUE #205: Graph component displays 36 hours for selection of 2 days

### PR DESCRIPTION
**Pull request by ericcccsliu**
## Status:
:rocket: Ready

## Description

Fixes #205, fixes #204, fixes #201

other fixes: 
- removes weekdays from the threshold graph. Looked way too cluttered on mobile, and we can think of designing better ways to notify the user that the data shown is for the current day. 
- fixes "today" on the weather card—after dusk on the current day, the weather card moves to only show tomorrow and the day after tomorrow's forecasts. in this case, tomorrow was being mistakenly labeled as "today." fixed this by getting the weekday in the current timezone and matching it with the first day being displayed on the weather card.  

## Screenshots
Screen Shot 2023-04-10 at 4 36 00 PM
Screen Shot 2023-04-10 at 4 36 21 PM
Screen Shot 2023-04-10 at 4 36 41 PM
Screen Shot 2023-04-10 at 4 36 53 PM

### CODE REVIEW

File: components/dashboard-modules/ExpectedTotalOutput.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const ExpectedTotalOutput: FC<{ siteUUID: string }> = ({ siteUUID }) => {
       value={
         forecastData
           ? getTotalExpectedOutput(forecastData.forecast_values)
-              .toFixed(2)
+              .toFixed(0)
```
Comment (AndrewLester) [inline components/dashboard-modules/ExpectedTotalOutput.tsx]: Can this be replaced with a Math.round()?

`Math.round(getTotalExpectedOutput(forecastData.forecast_values)).toString() + ' kWh'`

File: components/dashboard-modules/NumberDisplay.tsx [hunk 2]
```diff
@@ -10,15 +10,13 @@ interface Props {
 
 const NumberDisplay: FC<Props> = ({ title, value, onClick, isLoading }) => {
   //isLoading = !isLoading;
-  const Element = onClick ? 'button' : 'div';
```
Comment (AndrewLester) [inline components/dashboard-modules/NumberDisplay.tsx:13]: What's the value in removing this `Element` system?

File: components/dashboard-modules/SunnyTimeframe.tsx [hunk 3]
```diff
@@ -11,10 +11,15 @@ import { hoursToMinutes, millisecondsToHours } from 'date-fns';
...
 const SunnyTimeframe: FC<{ siteUUID: string }> = ({ siteUUID }) => {
-  const { forecastData, isLoading } = useSiteData(siteUUID);
+  const { forecastData, isLoading, installed_capacity_kw } =
+    useSiteData(siteUUID);
   const [isRelativeTime, setIsRelativeTime] = useState(false);
   const { timeFormatter } = useDateFormatter(siteUUID);
 
+  const thresholdCapacityKW = installed_capacity_kw
+    ? installed_capacity_kw * graphThreshold
+    : 0;
```
Comment (AndrewLester) [inline components/dashboard-modules/SunnyTimeframe.tsx:21]: Thanks

**Review by AndrewLester — APPROVED** [review]

**Review by AndrewLester — APPROVED** [review]

File: components/dashboard-modules/ExpectedTotalOutput.tsx (hunk 1 above)
Comment (ericcccsliu) [reply components/dashboard-modules/ExpectedTotalOutput.tsx]: think it might be better to keep it as `toFixed` for consistency, since we've been using it a lot?

File: components/dashboard-modules/NumberDisplay.tsx (hunk 2 above)
Comment (ericcccsliu) [reply components/dashboard-modules/NumberDisplay.tsx:13]: Honestly I removed it as part of trying to figure out what the heck was going wrong—I can put it back in before merging, since I do like how it keeps things consistent

Comment (ericcccsliu) [reply components/dashboard-modules/NumberDisplay.tsx:13]: Oh wait no I can't trivially put it back—if onClick is present, I'm wrapping the numberdisplay in a button

Comment (AndrewLester) [reply components/dashboard-modules/NumberDisplay.tsx:13]: Yeah this separation into a function works.

File: components/dashboard-modules/ExpectedTotalOutput.tsx (hunk 1 above)
Comment (AndrewLester) [reply components/dashboard-modules/ExpectedTotalOutput.tsx]: Since `Math.round()` is a more well-known and obvious function to read, I think it makes sense to use it where possible. When I see a `toFixed` call I expect to see some amount of decimals, just because that's its primary use.

**Review by AndrewLester — APPROVED** [review]
Imo switch toFixed(0) to Math.round, but not super important
