### PR TITLE
Separate logic in LocationInput and fix border radius

### LINKED ISSUE #222: Graph Markers and Legend should be hidden on page load
**Describe the bug**
Screenshot 2023-04-17 at 8 49 38 PM

The graph markers and legend on the dashboard aren't hidden on page load.

**To Reproduce**

1. Go to [http://localhost:3000/dashboard/35287](http://localhost:3000/dashboard/35287)

**Expected behavior**
To remain consistent with the rest of the screen's skeleton screen, we should hide the legends shown on the screen

### LINKED ISSUE #261: map doesn't show popup for locations outside the uk
**Describe the bug**
we had a popup that said "only locations in the UK are currently supported" that would activate on the map if you were zoomed in to locations outside the UK. this stopped working for whatever reason.

### PR DESCRIPTION
**Pull request by AndrewLester**
## Status:

:rocket: Ready

## Description

Fixes #<number>

### CODE REVIEW

File: lib/utils.ts [hunk 1]
```diff
@@ -111,3 +112,51 @@ export function hyphensToTitleCase(page: string) {
...
+
+    // After selecting a feature, re-focus the textarea and set
+    // cursor at start.
+    geocoderPrivate._inputEl.scrollLeft = 0;
+    geocoderPrivate.lastSelected = JSON.stringify(selected);
+
+    geocoderPrivate._eventEmitter.emit('result', {
+      result: selected,
+    });
+    geocoderPrivate.eventManager.select(selected, geocoder as any);
```
Comment (ericcccsliu) [inline lib/utils.ts:158]: awesome

File: lib/components/form/LocationInput.tsx [hunk 2]
```diff
@@ -1,262 +1,215 @@
...
 import { LatitudeLongitude } from '~/lib/types';
+import { reverseGeocodeWithoutFocus } from '~/lib/utils';
+
+mapboxgl.accessToken = process.env.NEXT_PUBLIC_MAPBOX_PUBLIC!;
 
 interface LocationInputProps {
-  originalLng: number;
-  originalLat: number;
-  shouldZoomIntoOriginal: boolean;
-  setIsSubmissionEnabled: (isSubmissionEnabled: boolean) => void;
```
Comment (ericcccsliu) [inline lib/components/form/LocationInput.tsx:11]: removing this allows anything to be inputted in the map—next button is enabled even when outside zoom threshold and also when completely outside of the UK

File: lib/components/form/LocationInput.tsx [hunk 3]
```diff
@@ -1,262 +1,215 @@
...
-            closeButton: false,
-            className: 'site-map',
-          })
-            .setLngLat([savedLng, savedLat])
-            .setHTML('<p>Drag map to pinpoint exact location.</p>')
-            .addTo(map.current);
-        }
-      }
-      setIsMoving(false);
-      setIsPastZoomThreshold(isPastZoomThreshold);
```
Comment (ericcccsliu) [inline lib/components/form/LocationInput.tsx:223]: consider bringing this behavior back (where submission is disabled while moving or while not past zoom threshold) since this resolved some bugs in the past

**Review by ericcccsliu — CHANGES_REQUESTED** [review]
great stuff—just would like to get the submission disabling behavior back on the map

File: lib/components/form/LocationInput.tsx (hunk 3 above)
Comment (AndrewLester) [reply lib/components/form/LocationInput.tsx:223]: From some quick testing I haven't been getting the issue. Since there are now `off` calls to turn off event listeners once the `LocationInput` unmounts, these should be fixed.

**Review by ericcccsliu — APPROVED** [review]
